version: '3'  
services: 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 5007:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./backups:/backups
      #- ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
    environment:
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086  # Ensures InfluxDB listens on port 8086 inside the container
      #- INFLUXDB_LOG_LEVEL=info
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=didioffside
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdbpass12345
      - DOCKER_INFLUXDB_INIT_BUCKET=Second_Logs
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=InfluxDBToken
    networks:
      - monitoring

  #backup:
   ##image: influxdb:latest
    #volumes:
     # - ./backups:/backups
      #- ./backup_script.sh:/backup_script.sh:ro
    #entrypoint: /bin/sh -c "/backup_script.sh"
    #environment:
     # - INFLUX_HOST=http://influxdb:8086
      #- INFLUX_TOKEN=InfluxDBToken=value
    #networks:
     # - monitoring

volumes:
  influxdb-data:
    driver: local

networks:
  monitoring:
    name: monitoring
    #driver: overlay