version: '3' 
services:
  service1:
    build: ./service1
    #image: didioffside/service1:latest
    container_name: service1
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./service1/aux_files:/aux_files
    ports:
      - 5000:5000
    networks:
      - service_network
  
  service2:
    #image: didioffside/service2:latest
    build: ./service2
    container_name: service2
    ports:
      - 5001:5001
    networks:
      - service_network
      
  
  service3:
    image: didioffside/service3:latest
    container_name: service3
    ports:
      - 5006:5006
    networks:
      - service_network

  service4:
    image: didioffside/service4:latest
    container_name: service4
    ports:
      - 5004:5004
    networks:
      - service_network
  
  #simulations:
   # build: ./sim_anomalies
    #container_name: sim
    #cap_add:
    #  - NET_ADMIN
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #networks:
    #  - service_network

networks:
  service_network:
    name: service_network
    driver: bridge